const {chromium}=require('playwright');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.MPL_TEST_BROWSER?{executablePath:process.env.MPL_TEST_BROWSER}:{channel:'msedge'})});const page=await browser.newPage({viewport:{width:1500,height:1000}});await page.route('**/*',r=>r.abort());await page.route('https://collection.test/**',r=>r.fulfill({contentType:'text/html',body:'<html></html>'}));await page.goto('https://collection.test/');
await page.setContent(fs.readFileSync('web/index.html','utf8').replace(/<script[^>]*><\/script>/g,'').replace(/<link[^>]*>/g,''));
await page.addStyleTag({content:fs.readFileSync('web/style.css','utf8')});
let source=fs.readFileSync('web/app.js','utf8');source=source.slice(0,source.lastIndexOf('restoreSidebar();'));
await page.addScriptTag({content:source});
await page.evaluate(()=>{db={version:UI_VERSION,settings:{columns:['image','brand','model','inv'],custom_fields:[],options:{},views:[]},records:[],catalog:[{id:'nokia',category:'brand',name:'Nokia',description:'',specs:{}},{id:'os',category:'os',name:'Symbian OS 9.2',description:'',specs:{}}],trash:[]};document.getElementById('application').hidden=false;addPhone();});
assert.equal(await page.locator('[data-effective=type]').count(),1);assert.equal(await page.locator('[data-effective=alias]').count(),1);assert.equal(await page.locator('[data-effective=gsm]').count(),1);assert.equal(await page.locator('[data-u=note]').count(),1);assert.equal(await page.locator('#gallery-upload').count(),0);
const os=page.locator('.catalog-combo[data-category=os] [data-combo-query]');await os.fill('Symbian OS 9.');assert.equal(await page.locator('.catalog-combo[data-category=os] [role=option]').first().textContent(),'Symbian OS 9.2');await page.locator('.catalog-combo[data-category=os] [role=option]').first().click();assert.equal(await page.locator('[data-effective=os]').inputValue(),'Symbian OS 9.2');await os.fill('Symbian OS 9.1');assert.equal(await os.evaluate(el=>el.checkValidity()),false);await os.fill('Symbian OS 9.2');await page.keyboard.press('Escape');assert.equal(await page.locator('#editor').evaluate(el=>el.open),true);
await page.evaluate(()=>{readDraft();});assert.equal(await page.evaluate(()=>draft.os),'Symbian OS 9.2');
// Existing model edits keep sibling overrides and legacy gallery data.
await page.evaluate(()=>{document.getElementById('editor').close();db.records=[{id:'a',kind:'phone',brand:'Nokia',model:'N73',alias:'N73-1',type:'RM-133',os:'Symbian OS 9.2',photos:['/media/old.jpg'],custom:{},instances:[{id:'u1',inv:'1',photos:[],type:''},{id:'u2',inv:'2',photos:[],type:'RM-ME'}]}];showEditor('a',1);});
await page.locator('[data-effective=type]').fill('RM-new');await page.locator('#editor-unit-select').selectOption('0');assert.equal(await page.locator('[data-effective=type]').inputValue(),'RM-133');assert.equal(await page.evaluate(()=>draft.instances[1].type),'RM-new');assert.equal(await page.evaluate(()=>draft.photos[0]),'/media/old.jpg');
await page.evaluate(()=>{dirty=false;closeEditor();sidebarState(true);});assert.equal(await page.locator('main').evaluate(el=>getComputedStyle(el).marginLeft),'0px');
// Empty and cleared phone forms must not block installation; real drafts must.
await page.evaluate(()=>{phoneDraft=null;catalogReturn=null;panelDirty=false;addPhone();closeEditor();});assert.equal(await page.evaluate(()=>hasUnsavedWork()),false);
await page.evaluate(()=>addPhone());await page.locator('[data-r=model]').fill('Unsaved test phone');await page.evaluate(()=>closeEditor());assert.equal(await page.evaluate(()=>hasUnsavedWork()),true);assert.match(await page.evaluate(()=>unsavedWorkReasons().join(' ')),/Add phone draft/);
page.once('dialog',d=>d.accept());await page.evaluate(()=>{addPhone();clearPhoneDraft();closeEditor();});assert.equal(await page.evaluate(()=>hasUnsavedWork()),false);assert.equal(await page.evaluate(()=>phoneDraft),null);
console.log('Update guard: untouched and cleared forms allow updates; real drafts identify Add phone as the source.');
// A long catalog must scroll inside Settings with aligned compact columns.
await page.evaluate(()=>{db.catalog.push(...Array.from({length:50},(_,i)=>({id:'brand'+i,category:'brand',name:i%2?'Sony Ericsson '+i:'Nokia '+i,description:i%2?'A description':'',specs:i%2?{Origin:'Test'}:{}})));catalogList('brand');});
await page.locator('[data-catalog-section=brand] .catalog-item-row').last().scrollIntoViewIfNeeded();
assert.equal(await page.locator('#panel-body').evaluate(el=>el.scrollTop>0&&el.scrollHeight>el.clientHeight),true);
const positions=await page.locator('[data-catalog-section=brand] .catalog-item-row').evaluateAll(rows=>rows.slice(0,3).map(r=>({height:r.getBoundingClientRect().height,x:[...r.children].map(c=>c.getBoundingClientRect().x)})));
assert.deepEqual(positions[0].x,positions[1].x);assert.deepEqual(positions[1].x,positions[2].x);assert.ok(positions.every(r=>r.height<=38));
await page.locator('[data-action=catalog-toggle][data-category=os]').click();assert.equal(await page.locator('[data-catalog-section=brand]').isVisible(),false);assert.equal(await page.locator('[data-catalog-section=os]').isVisible(),true);
console.log('Catalog DOM: long list scrolls, columns align, compact rows and single expanded category passed.');
// Filters use a single matching physical unit, and code searches ignore punctuation.
await page.evaluate(()=>{quickFilters={brand:'Nokia',color:'Black',os:'',location:'Shelf',state:''};});
assert.equal(await page.evaluate(()=>searchMatches({kind:'phone',brand:'Nokia',model:'N97 Mini',type:'RM-555',instances:[{color:'Black',location:'Box'},{color:'Silver',location:'Shelf'}]},'RM555')),false);
await page.evaluate(()=>quickFilters.location='Box');assert.equal(await page.evaluate(()=>searchMatches({kind:'phone',brand:'Nokia',model:'N97 Mini',type:'RM-555',instances:[{color:'Black',location:'Box',product_code:'0591234'}]},'Nokia RM555 0591234')),true);
// Choosing a photo changes only that unit; save-and-next submits and clears identifiers.
await page.evaluate(()=>{$('panel').close();panelRoute=null;panelDirty=false;phoneDraft=null;catalogReturn=null;quickFilters={};db.records[0].instances[0].photos=['https://example.com/a.jpg','https://example.com/b.jpg'];showEditor('a',0);});
await page.locator('[data-action=main-unit-photo]').click();assert.equal(await page.evaluate(()=>draft.instances[0].photos[0]),'https://example.com/b.jpg');
await page.evaluate(()=>{api=async(path,data)=>{if(path==='/api/record'){const r=clone(data.record);r.rev=2;db.records=[r];return r;}if(path==='/api/data')return db;return {};};});
await page.locator('#save-add-another').click();assert.equal(await page.locator('#editor').evaluate(el=>el.open),true);assert.equal(await page.evaluate(()=>mode),'add');assert.equal(await page.evaluate(()=>draft.instances.length),3);assert.equal(await page.evaluate(()=>addUnit.inv),'3');assert.equal(await page.evaluate(()=>addUnit.imei||''),'');assert.equal(await page.evaluate(()=>addUnit.photos.length),0);assert.equal(await page.evaluate(()=>db.records[0].instances[0].photos[0]),'https://example.com/b.jpg');
console.log('Filters, code search, main photo and Save and add another passed.');
await page.evaluate(()=>{dirty=false;phoneDraft=null;$('editor').close();db.records[0].battery='BL-6F';db.catalog.push({id:'bl6f',category:'battery',name:'BL-6F',description:'retained legacy description',source:'https://example.com',specs:{Legacy:'keep'},compatible:[]});catalogEditor('battery','bl6f');});
assert.equal(await page.locator('[data-battery-spec]').count(),9);assert.equal(await page.locator('#catalog-source').count(),1);assert.equal(await page.locator('#catalog-description').count(),1);assert.equal(await page.locator('[data-catalog-compatible]').count(),0);assert.ok((await page.locator('#panel-body').textContent()).includes('N73'));
await page.locator('[data-battery-spec=Voltage]').fill('3.7V');
await page.evaluate(()=>{api=async(path,data)=>{if(path==='/api/catalog'){db.catalog=db.catalog.map(x=>x.id===data.id?data:x);return data;}if(path==='/api/data')return db;return {};};});
await page.locator('[data-action=catalog-save]').click();assert.equal(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').specs.Voltage),'3.7V');assert.equal(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').specs.Legacy),'keep');assert.equal(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').description),'retained legacy description');
console.log('Battery properties, automatic models and preservation of hidden legacy data passed.');
// A real narrow viewport must show readable units instead of compressed desktop columns.
await page.evaluate(()=>{$('panel').close();panelRoute=null;panelDirty=false;dirty=false;currentView='all';db.settings.layout='list';db.settings.columns=columns.map(c=>c[0]);db.records[0].instances[0].box=true;db.records[0].instances[0].charger_present=false;db.records[0].instances[0].state='Ispravan';expanded.add('a');render();});
await page.setViewportSize({width:393,height:851});
assert.equal(await page.locator('#table-wrap').isVisible(),false);assert.equal(await page.locator('#mobile-list').isVisible(),true);
assert.equal(await page.locator('#quick-filters').isVisible(),false);await page.locator('#filter-toggle').click();assert.equal(await page.locator('#quick-filters').isVisible(),true);await page.locator('#filter-toggle').click();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
assert.equal(await page.locator('.mobile-primary-nav').evaluate(el=>el.getBoundingClientRect().height),66);
assert.ok(await page.locator('#mobile-list .state-working').count()>0);
assert.equal(await page.locator('#collection-table th[data-column-key=state]').count(),0);
assert.ok(await page.locator('#collection-table .unit-details-table .state-working').count()>0);
await page.screenshot({path:'mobile-collection-113.png',fullPage:true});
await page.evaluate(()=>{currentView='incomplete';render();});assert.equal(await page.locator('#completion-report').isVisible(),true);assert.match(await page.locator('#completion-report').textContent(),/Missing: Charger/);
await page.evaluate(()=>{currentView='all';showEditor('a',0);});assert.equal(await page.locator('[data-r=declared_parts]').count(),0);await page.locator('[data-u=for_parts]').check();await page.evaluate(()=>readDraft());assert.equal(await page.evaluate(()=>draft.instances[0].purpose),'Donor');await page.locator('[data-u=for_parts]').uncheck();await page.evaluate(()=>readDraft());assert.equal(await page.evaluate(()=>draft.instances[0].purpose),'Kolekcija');
console.log('Mobile widths, collapsed filters, bottom navigation, unit-only status, boxed completion and donor checkbox passed.');
await page.evaluate(()=>{dirty=false;$('editor').close();db.catalog.push({id:'alt1',category:'battery',name:'Test alternative 1',specs:{},compatible_batteries:[]},{id:'alt2',category:'battery',name:'Test alternative 2',specs:{},compatible_batteries:[]});catalogEditor('battery','bl6f');});
await page.locator('[data-battery-compatible=alt1]').check();await page.locator('[data-battery-compatible=alt2]').check();await page.locator('[data-action=catalog-save]').click();
assert.deepEqual(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').compatible_batteries),['alt1','alt2']);
assert.match(await page.evaluate(()=>batteryCell('BL-6F')),/Test alternative 1/);assert.match(await page.evaluate(()=>batteryCell('BL-6F')),/Test alternative 2/);
assert.match(await page.evaluate(()=>catalogItems('battery')),/Nominal Capacity/);assert.match(await page.evaluate(()=>catalogItems('battery')),/3.7V/);
await page.evaluate(()=>{$('panel').close();panelDirty=false;panelRoute=null;render();});await page.setViewportSize({width:1700,height:950});
assert.equal(await page.locator('#collection-table .unit-table-row [data-column=os]').first().evaluate(el=>getComputedStyle(el).whiteSpace),'normal');
assert.equal(await page.locator('#collection-table .unit-extra-row').count(),0);
await page.evaluate(()=>{db.records[0].os='Symbian OS 9.2, S60 rel. 3.1';db.records[0].instances[0].os='';db.records[0].instances[0].location='On shelf';render();});
const row=page.locator('#collection-table .unit-table-row').first();
for(const key of ['location','box','state','rating','note'])assert.equal(await row.locator('[data-column='+key+']').count(),1);
const osCell=row.locator('[data-column=os]');
assert.match(await osCell.textContent(),/Symbian OS 9.2, S60 rel. 3.1/);
assert.equal(await osCell.locator('button').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.equal(await row.locator('[data-column=image] small').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
await page.screenshot({path:'desktop-collection-114.png',fullPage:true});
console.log('Battery summaries, multi-selection, automatic alternatives and compact expanded rows passed.');
await page.setViewportSize({width:393,height:851});
await page.evaluate(async()=>{settingsTab='appearance';panelDirty=false;await settingsPanel();});
const save=page.locator('[data-action=save-settings]');
await save.scrollIntoViewIfNeeded();
const bounds=await save.boundingBox(),navBounds=await page.locator('.mobile-primary-nav').boundingBox();
assert.ok(bounds.y+bounds.height<=navBounds.y,'Save button must stay above mobile navigation');
assert.equal(await page.locator('.theme-picker').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),2);
assert.ok(await page.locator('#panel-body').evaluate(el=>el.scrollTop>0));
await page.locator('#panel-body').evaluate(el=>el.scrollTop=0);
assert.equal(await page.locator('#panel-body').evaluate(el=>el.scrollTop),0);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'mobile-settings-115.png',fullPage:true});
console.log('Mobile Settings: single-column themes, reachable Save above bottom navigation and scrolling back to top passed.');
// New phone suggestions select a real catalog value without losing the draft.
await page.evaluate(entries=>{ $('panel').close();$('editor').close();db.catalog=[{id:'nokia',category:'brand',name:'Nokia',specs:{}},...entries.map(e=>({...e,id:e.name,category:'battery',compatible_batteries:e.compatible_names}))];phoneDraft=null;addPhone();draft.brand='Nokia';draft.model='N95 8GB';editorRender();},JSON.parse(fs.readFileSync('data/nokia-batteries.json','utf8')).entries);
await page.locator('[data-action="choose-battery-suggestion"][data-value="BL-6F"]').click();
assert.equal(await page.locator('[data-r="battery"]').inputValue(),'BL-6F');
await page.locator('[data-r="model"]').fill('N95');
assert.equal(await page.locator('[data-action="choose-battery-suggestion"][data-value="BL-5F"]').count(),1);
assert.equal(await page.locator('[data-action="choose-battery-suggestion"][data-value="BL-6F"]').count(),0);
assert.equal(await page.locator('[data-r="battery"]').inputValue(),'BL-6F'); // suggestions never overwrite the user's selection
await page.evaluate(()=>{$('editor').close();catalogEditor('battery','BL-4U');});
assert.match(await page.locator('#catalog-description').inputValue(),/Asha 500/);
assert.equal(await page.locator('#catalog-source').inputValue(),'https://lpcwiki.miraheze.org/wiki/Nokia_BL-4U');
console.log('DOM: battery suggestions, variant changes, explicit selection and source notes passed.');
// Wishlist records have no units; acquisition is committed only after Save.
await page.setViewportSize({width:1500,height:1000});
await page.evaluate(()=>{$('panel').close();$('editor').close();panelRoute=null;panelDirty=false;phoneDraft=null;dirty=false;currentView='wish';showWanted=false;quickFilters={};db.records=[];db.catalog.push({id:'two-mm',category:'charger',name:'2mm',compatible:[]});
 window.failWishlistSave=false;
 api=async(path,data)=>{if(path==='/api/record'){if(window.failWishlistSave)throw Error('Simulated save conflict');const r=clone(data.record);r.id=r.id||'wanted-dom';r.rev=(r.rev||0)+1;r.instances.forEach((u,i)=>u.id=u.id||'unit-'+i);db.records=db.records.filter(x=>x.id!==r.id).concat([r]);return r;}if(path==='/api/data')return db;return {};};render();});
await page.locator('#add-wanted').click();
await page.locator('.catalog-combo[data-category=brand] [data-combo-query]').fill('Nokia');
await page.locator('.catalog-combo[data-category=brand] [role=option]').filter({hasText:'Nokia'}).first().click();
await page.locator('[data-r=model]').fill('N95 8GB');await page.locator('[data-r=model]').press('Tab');
await page.locator('[data-action=choose-battery-suggestion][data-value="BL-6F"]').click();
await page.locator('[data-r=alias]').fill('N95-2');
assert.equal(await page.locator('[data-u=imei]').count(),0);
await page.locator('#record-save').click();
await page.waitForFunction(()=>!$('editor').open);
assert.equal(await page.evaluate(()=>db.records[0].instances.length),0);
assert.equal(await page.evaluate(()=>db.records[0].wishlist),true);
await page.evaluate(()=>{currentView='all';render();});
assert.equal(await page.locator('#table-wrap').isVisible(),false);
await page.locator('#wanted-toggle').click();assert.equal(await page.locator('#table-wrap').isVisible(),true);
assert.match(await page.locator('#summary').textContent(),/0models0phones/);
await page.setViewportSize({width:393,height:851});
assert.equal(await page.locator('#mobile-list [data-action=acquire-wanted]').isVisible(),true);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'mobile-wishlist-118.png',fullPage:true});
await page.locator('#mobile-list [data-action=acquire-wanted]').click();
await page.locator('#editor [data-action=close-editor]').first().click();assert.equal(await page.evaluate(()=>db.records[0].wishlist),true);
await page.locator('#mobile-list [data-action=acquire-wanted]').click();
await page.locator('[data-u=imei]').fill('987654321012345');
await page.evaluate(()=>window.failWishlistSave=true);await page.locator('#record-save').click();
assert.match(await page.locator('#editor-error').textContent(),/Simulated save conflict/);
assert.equal(await page.evaluate(()=>db.records[0].instances.length),0);
await page.evaluate(()=>window.failWishlistSave=false);await page.locator('#record-save').click();await page.waitForFunction(()=>!$('editor').open);
assert.equal(await page.evaluate(()=>db.records[0].wishlist),false);assert.equal(await page.evaluate(()=>db.records[0].instances.length),1);
await page.evaluate(()=>{currentView='wish';render();});assert.equal(await page.evaluate(()=>filtered().length),0);
await page.evaluate(()=>{currentView='all';showWanted=false;render();addPhone();});
await page.locator('.catalog-combo[data-category=brand] [data-combo-query]').fill('Nokia');await page.locator('.catalog-combo[data-category=brand] [role=option]').filter({hasText:'Nokia'}).first().click();
await page.locator('[data-r=model]').fill('N95 8GB');await page.locator('[data-r=model]').press('Tab');
assert.equal(await page.locator('[data-effective=alias]').inputValue(),'N95-2');assert.equal(await page.locator('[data-r=battery]').inputValue(),'BL-6F');
await page.locator('[data-u=imei]').fill('987654321012345');await page.locator('[data-u=imei]').press('Tab');assert.match(await page.locator('#imei-warning').textContent(),/Duplicate IMEI/);
await page.evaluate(()=>{dirty=false;$('editor').close();phoneDraft=null;const r=db.records[0];r.instances[0].box=null;r.instances[0].battery_present=false;db.records.push({id:'spare',kind:'part',model:'Spare BL-6F',catalog_item:'BL-6F',quantity:2,reserved:1,location:'Shelf',instances:[]});currentView='incomplete';render();});
assert.match(await page.locator('#completion-report').textContent(),/Missing: Battery/);assert.match(await page.locator('#completion-report').textContent(),/1 available/);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'mobile-missing-118.png',fullPage:true});
console.log('DOM: wishlist create/show/hide, mobile acquisition/cancel/conflict, known model prefill, duplicate IMEI and missing stock passed.');
// Each layout presents the same records without changing shared settings/data.
await page.evaluate(()=>{currentView='all';quickFilters={};showWanted=false;expanded.add(db.records[0].id);window.layoutBefore=JSON.stringify(db.records);window.serverLayoutBefore=db.settings.layout;});
for(const width of [1500,393,320]){
 await page.setViewportSize({width,height:950});
 for(const choice of ['grouped','split','model-cards','compact','gallery']){
  await page.evaluate(key=>setCollectionLayout(key),choice);
  assert.equal(await page.locator('#alternative-layout').isVisible(),true,choice);
  assert.equal(await page.locator('#table-wrap').isVisible(),false,choice);
  assert.equal(await page.locator('#mobile-list').isVisible(),false,choice);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,choice+' at '+width);
  assert.equal(await page.evaluate(()=>JSON.stringify(db.records)===window.layoutBefore),true);
  assert.equal(await page.evaluate(()=>db.settings.layout===window.serverLayoutBefore),true);
 }
}
await page.setViewportSize({width:1500,height:950});
await page.evaluate(()=>{setCollectionLayout('grouped');});
await page.locator('#alternative-layout .layout-unit .row-menu-toggle').first().click();await page.locator('#alternative-layout [data-action=edit-unit]').first().click();assert.equal(await page.locator('#editor').evaluate(e=>e.open),true);
await page.evaluate(()=>{dirty=false;$('editor').close();currentView='incomplete';render();});assert.equal(await page.locator('#alternative-layout').isVisible(),false);assert.equal(await page.locator('#completion-report').isVisible(),true);
await page.evaluate(()=>{currentView='all';setCollectionLayout('list');});assert.equal(await page.locator('#table-wrap').isVisible(),true);
await page.evaluate(()=>{settingsTab='appearance';panelDirty=false;settingsPanel();});
assert.equal(await page.locator('#default-layout option').count(),7);
await page.locator('#default-layout').selectOption('compact');
assert.equal(await page.evaluate(()=>collectionLayout),'compact');assert.equal(await page.evaluate(()=>localStorage.getItem('mpl-collection-layout')),'compact');
assert.equal(await page.evaluate(()=>panelDirty),false);
await page.locator('.layout-choices [data-layout=list]').click();assert.equal(await page.locator('#default-layout').inputValue(),'list');
await page.screenshot({path:'layout-settings-119.png',fullPage:true});
await page.evaluate(()=>{$('panel').close();setCollectionLayout('grouped');});
await page.screenshot({path:'layout-grouped-119.png',fullPage:true});
// Collection planning and compact toolbar interactions.
await page.evaluate(()=>{currentView='all';quickFilters={};$('search').value='';selectedUnits.clear();setCollectionLayout('list');});
for(const width of [1500,393,320]){await page.setViewportSize({width,height:950});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'toolbar '+width);}
await page.setViewportSize({width:1500,height:950});
await page.locator('.collection-controls [data-action=saved-filters]').click();
await page.locator('#saved-filter-name').fill('Missing battery');
await page.evaluate(()=>{quickFilters={battery_present:'false'};const previousAPI=api;api=async(path,data)=>{if(path==='/api/settings'){Object.assign(db.settings,data);return db.settings;}return previousAPI(path,data);};});
await page.locator('[data-action=save-view]').click();
assert.equal(await page.evaluate(()=>db.settings.views.at(-1).quickFilters.battery_present),'false');
await page.evaluate(()=>{quickFilters={};});
await page.locator('[data-action=apply-saved-filter]').last().click();assert.equal(await page.evaluate(()=>quickFilters.battery_present),'false');
await page.evaluate(()=>{quickFilters={};render();});
await page.locator('.collection-controls [data-action=locations]').click();assert.equal(await page.locator('#panel-title').textContent(),'Locations');
await page.evaluate(()=>{$('panel').close();panelDirty=false;const r=db.records.find(r=>r.kind==='phone'&&live(r).length);const u=clone(live(r)[0]);u.id='compare-test';u.inv='C2';u.battery_present=false;u.note='Different condition';r.instances.push(u);selectedUnits=new Set([r.instances[0].id,u.id]);render();});
await page.locator('.collection-controls [data-action=compare-units]').click();assert.ok(await page.locator('.comparison-different').count()>0);
await page.evaluate(()=>{$('panel').close();selectedUnits.clear();addWanted();draft.brand='Nokia';draft.model='Wishlist plan';editorRender();});
await page.locator('[data-r=wish_priority]').selectOption('High');await page.locator('[data-r=wish_price]').fill('150');await page.locator('[data-r=wish_note]').fill('Original box and silver housing');
await page.evaluate(()=>{readDraft();window.savedPlan=clone(draft);});assert.equal(await page.evaluate(()=>window.savedPlan.wish_priority),'High');assert.equal(await page.evaluate(()=>window.savedPlan.wish_note),'Original box and silver housing');
await page.evaluate(()=>{dirty=false;$('editor').close();setCollectionLayout('grouped');});
await page.screenshot({path:'collection-toolbar-120.png',fullPage:true});
console.log('DOM: compact toolbar widths, saved filter save/apply, locations, comparison and wishlist fields passed.');

// Every editable record/unit field has its own persistent verification marker.
await page.evaluate(()=>{phoneDraft=null;addPhone();draft.to_check=['note'];draft.instances[0].to_check=['note'];editorRender();});
assert.equal(await page.locator('[data-check-field=note][data-check-index=model]').count(),1);assert.equal(await page.locator('[data-check-field=note][data-check-index="0"]').count(),1);await page.evaluate(()=>{dirty=false;$('editor').close();});
await page.evaluate(()=>{phoneDraft=null;catalogReturn=null;panelDirty=false;$('panel').close();addPhone();draft.brand='Nokia';draft.model='Review fields';db.settings.custom_fields=[{id:'test-extra',label:'Extra field',type:'text'}];editorRender();});
assert.equal(await page.locator('[data-check-field=os]').count(),1);
assert.equal(await page.locator('[data-check-field="custom:test-extra"]').count(),1);
const coverage=await page.evaluate(()=>[...$('editor-content').querySelectorAll('[data-r],[data-u],[data-effective],[data-custom]')].every(el=>!!el.closest('.checkable-field')?.querySelector('[data-check-field]')));assert.equal(coverage,true);
await page.locator('[data-check-field=os]').check();await page.locator('[data-check-field=imei]').check();await page.locator('[data-check-field="custom:test-extra"]').check();
await page.evaluate(()=>{readDraft();window.checkDraft=clone(draft);});assert.equal(await page.evaluate(()=>window.checkDraft.to_check.includes('os')),true);assert.equal(await page.evaluate(()=>window.checkDraft.instances[0].to_check.includes('imei')),true);
await page.locator('#record-save').click();assert.equal(await page.locator('#editor').evaluate(e=>e.open),false);
await page.evaluate(()=>{window.reviewRecord=db.records.find(r=>r.model==='Review fields');showEditor(window.reviewRecord.id,0);});
assert.equal(await page.locator('[data-check-field=os]').isChecked(),true);assert.equal(await page.locator('[data-check-field=imei]').isChecked(),true);
for(const width of [1500,393,320]){await page.setViewportSize({width,height:950});assert.equal(await page.evaluate(()=>$('editor').scrollWidth<=$('editor').clientWidth+1),true,'review editor at '+width);}
await page.setViewportSize({width:1500,height:950});await page.screenshot({path:'field-checks-121.png',fullPage:true});
await page.locator('[data-check-field=imei]').uncheck();await page.locator('#record-save').click();assert.equal(await page.evaluate(()=>db.records.find(r=>r.model==='Review fields').instances[0].to_check.includes('imei')),false);
await page.evaluate(()=>{currentView='all';quickFilters={};$('search').value='';setCollectionLayout('list');window.beforeFocus=JSON.stringify(db.records);});
await page.locator('#check-toggle').click();assert.equal(await page.locator('html').getAttribute('data-check-focus'),'true');assert.equal(await page.evaluate(()=>JSON.stringify(db.records)),await page.evaluate(()=>window.beforeFocus));
await page.screenshot({path:'check-focus-121.png',fullPage:true});
await page.locator('#check-toggle').click();assert.equal(await page.locator('html').getAttribute('data-check-focus'),'false');assert.equal(await page.evaluate(()=>JSON.stringify(db.records)),await page.evaluate(()=>window.beforeFocus));
await page.evaluate(()=>{const source=db.records.find(r=>r.model==='Review fields');db.records.push(...Array.from({length:5},(_,i)=>({...clone(source),id:'cross'+i,model:'Model '+i,os:'OS '+i,instances:[{...clone(source.instances[0]),id:'cross-unit'+i,inv:'X'+i}]})));selectedUnits=new Set(db.records.filter(r=>r.kind==='phone').flatMap(r=>r.instances.map(u=>u.id)));compareUnits();});
assert.ok(await page.locator('.comparison-table thead th').count()>5);assert.ok((await page.locator('.comparison-table').textContent()).includes('OS 4'));
await page.setViewportSize({width:393,height:950});assert.equal(await page.locator('.comparison-scroll').evaluate(el=>el.scrollWidth>el.clientWidth),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
await page.evaluate(()=>{$('panel').close();db.settings.custom_fields=[];selectedUnits.clear();setCollectionLayout('grouped');});
console.log('DOM: all field markers incl. OS/custom fields, save/reopen/clear, mobile form, focus toggle immutability and cross-model comparison passed.');

// Compact actions, hover notes, lightweight inputs, and unit-specific trash requests.
await page.setViewportSize({width:1500,height:950});
await page.evaluate(()=>{dirty=false;$('editor').close();$('panel').close();currentView='all';collectionLayout='list';db.settings.columns=['image','brand','model','alias','editions','gsm','wiki','note','actions'];const r=db.records.find(x=>x.kind==='phone');r.note='Model note';r.gsm='https://example.com';r.instances[0].note='Small scratch on back';r.instances[0].edition='Music Edition';expanded.add(r.id);window.compactId=r.id;render();});
const firstUnit=page.locator('#collection-table .unit-table-row').first();
assert.equal(await firstUnit.locator('.row-menu-toggle').count(),1);
await firstUnit.locator('.row-menu-toggle').click();
assert.equal(await firstUnit.locator('.row-menu').evaluate(el=>el.matches(':popover-open')),true);
assert.match(await firstUnit.locator('.row-menu').textContent(),/Edit.*Copy.*Move this phone to trash/s);
await page.keyboard.press('Escape');assert.equal(await firstUnit.locator('.row-menu').evaluate(el=>el.matches(':popover-open')),false);
await firstUnit.locator('.note-icon').hover();assert.equal(await page.locator('#note-tooltip').textContent(),'Small scratch on back');assert.equal(await page.locator('#note-tooltip').evaluate(el=>el.matches(':popover-open')),true);
await page.locator('#search').hover();assert.equal(await page.locator('#note-tooltip').evaluate(el=>el.matches(':popover-open')),false);
assert.equal(await firstUnit.locator('[data-column=note]').textContent(),'▤');
assert.equal(await firstUnit.locator('[data-column=editions] .quick-edit').evaluate(el=>getComputedStyle(el).whiteSpace),'normal');
assert.ok(!(await page.locator('#collection-table [data-column=gsm]').first().textContent()).includes('↗'));
await page.screenshot({path:'compact-collection-122.png',fullPage:true});
await page.evaluate(()=>{showEditor(window.compactId,0);});
assert.equal(await page.locator('#editor [data-action=delete-unit]').count(),1);assert.equal(await page.locator('#editor [data-action=delete-record]').count(),0);
assert.equal(await page.locator('[data-u=imei2],[data-u=serial],[data-r=declared_qty]').count(),0);
assert.equal(await page.locator('[data-effective=alias]').getAttribute('placeholder'),'e.g. 6500s-1');
await page.evaluate(()=>{window.originalConfirm=window.confirm;window.confirm=()=>true;window.originalApi=api;window.originalRefresh=refresh;window.trashCall=null;api=async(path,body)=>{window.trashCall={path,body};return {ok:true};};refresh=async()=>{};});
await page.locator('#editor [data-action=delete-unit]').click();
assert.equal(await page.evaluate(()=>window.trashCall.path),'/api/trash-unit');assert.equal(await page.evaluate(()=>window.trashCall.body.unit),await page.evaluate(()=>record(window.compactId).instances[0].id));
await page.evaluate(()=>{api=window.originalApi;refresh=window.originalRefresh;window.confirm=window.originalConfirm;});
await page.setViewportSize({width:393,height:851});await page.evaluate(()=>render());
await page.locator('#mobile-list .mobile-unit .note-icon').first().click();assert.equal(await page.locator('#note-tooltip').evaluate(el=>el.matches(':popover-open')),true);
await page.locator('#search').click();assert.equal(await page.locator('#note-tooltip').evaluate(el=>el.matches(':popover-open')),false);
await page.locator('#mobile-list .mobile-unit .row-menu-toggle').first().click();assert.equal(await page.locator('#mobile-list .mobile-unit .row-menu').first().evaluate(el=>el.matches(':popover-open')),true);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.keyboard.press('Escape');
await page.evaluate(()=>setCollectionLayout('grouped'));
console.log('DOM: compact menu, notes hover/tap, wrapping, placeholders, removed fields and unit-specific delete passed.');

// Mixed model summaries use hover/focus on desktop and tap on mobile.
await page.setViewportSize({width:1500,height:950});
await page.evaluate(()=>{dirty=false;$('editor').close();$('panel').close();currentView='all';quickFilters={};showWanted=false;collectionLayout='list';db.settings.columns=['image','brand','model','alias','type','colors','editions','os','qty','actions'];db.records=[{id:'multiple-fixture',kind:'phone',brand:'Nokia',model:'6500 Slide',alias:'6500s-1',type:'RM-240',os:'S40 5th Edition',battery:'BP-5M',charger:'2mm',instances:['Black','Silver','White'].map((color,i)=>({id:'multi-'+i,inv:String(i+1),condition:'U kolekciji',state:'Netestiran',color,edition:i?'Music Edition':'Standard',alias:i===2?'6500s-2':'',os:i===2?'S40 revised':'',photos:[]}))}];expanded.add('multiple-fixture');window.summaryBefore=JSON.stringify(db.records);render();});
const modelColor=page.locator('#collection-table > tbody > tr').first().locator('[data-column=colors] .multiple-value');
assert.equal(await modelColor.textContent(),'Multiple');await modelColor.hover();assert.match(await page.locator('#note-tooltip').textContent(),/Black\nSilver\nWhite/);
await page.locator('#search').hover();assert.equal(await page.locator('#note-tooltip').evaluate(el=>el.matches(':popover-open')),false);
await modelColor.focus();assert.equal(await page.locator('#note-tooltip').evaluate(el=>el.matches(':popover-open')),true);await page.keyboard.press('Escape');
assert.equal(await page.locator('#collection-table .unit-table-row [data-column=colors] .multiple-value').count(),0);
assert.equal(await page.locator('#collection-table > tbody > tr').first().locator('[data-column=editions] .multiple-value').count(),1);
assert.equal(await page.locator('#collection-table > tbody > tr').first().locator('[data-column=type]').textContent(),'RM-240');
await page.screenshot({path:'model-summary-123.png',fullPage:true});
await page.setViewportSize({width:393,height:851});await page.locator('#mobile-list .mobile-model-meta .multiple-value').first().click();assert.match(await page.locator('#note-tooltip').textContent(),/Black\nSilver\nWhite/);await page.locator('#search').click();assert.equal(await page.locator('#note-tooltip').evaluate(el=>el.matches(':popover-open')),false);
for(const width of [1500,393,320]){await page.setViewportSize({width,height:950});for(const choice of ['grouped','split','model-cards','compact','gallery','cards']){await page.evaluate(key=>setCollectionLayout(key),choice);const root=choice==='cards'?'#card-grid':'#alternative-layout';assert.ok(await page.locator(root+' .multiple-value').count()>=2);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,choice+' '+width);}}
assert.equal(await page.evaluate(()=>JSON.stringify(db.records)===window.summaryBefore),true);
await page.evaluate(()=>setCollectionLayout('grouped'));
console.log('DOM: Multiple summaries, desktop hover/focus/Escape, mobile tap, individual values and seven layouts passed.');

// Local storage survives a page reload; a separate browser context stays Classic.
await page.reload();
await page.setContent(fs.readFileSync('web/index.html','utf8').replace(/<script[^>]*><\/script>/g,'').replace(/<link[^>]*>/g,''));await page.addScriptTag({content:source});
assert.equal(await page.evaluate(()=>collectionLayout),'grouped');
const isolated=await browser.newPage();await isolated.route('**/*',route=>route.fulfill({contentType:'text/html',body:'<html></html>'}));await isolated.goto('https://collection.test/');
await isolated.setContent(fs.readFileSync('web/index.html','utf8').replace(/<script[^>]*><\/script>/g,'').replace(/<link[^>]*>/g,''));await isolated.addScriptTag({content:source});assert.equal(await isolated.evaluate(()=>collectionLayout),'list');await isolated.close();
console.log('DOM: seven layouts, responsive widths, editing, missing view, local persistence and device isolation passed.');
console.log('DOM: one field per property, search/select/reject, Escape, effective unit switching, retained gallery, collapsed layout passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
