const {chromium}=require('playwright');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.MPL_TEST_BROWSER?{executablePath:process.env.MPL_TEST_BROWSER}:{channel:'msedge'})});const page=await browser.newPage({viewport:{width:1500,height:1000}});await page.route('**/*',r=>r.abort());
await page.setContent(fs.readFileSync('web/index.html','utf8').replace(/<script[^>]*><\/script>/g,'').replace(/<link[^>]*>/g,''));
await page.addStyleTag({content:fs.readFileSync('web/style.css','utf8')});
let source=fs.readFileSync('web/app.js','utf8');source=source.slice(0,source.lastIndexOf('restoreSidebar();'));
await page.addScriptTag({content:source});
await page.evaluate(()=>{db={version:UI_VERSION,settings:{columns:['image','brand','model','inv'],custom_fields:[],options:{},views:[]},records:[],catalog:[{id:'nokia',category:'brand',name:'Nokia',description:'',specs:{}},{id:'os',category:'os',name:'Symbian OS 9.2',description:'',specs:{}}],trash:[]};document.getElementById('application').hidden=false;addPhone();});
assert.equal(await page.locator('[data-effective=type]').count(),1);assert.equal(await page.locator('[data-effective=alias]').count(),1);assert.equal(await page.locator('[data-effective=gsm]').count(),1);assert.equal(await page.locator('[data-u=note]').count(),1);assert.equal(await page.locator('#gallery-upload').count(),0);
const os=page.locator('.catalog-combo[data-category=os] [data-combo-query]');await os.fill('Symbian OS 9.');assert.equal(await page.locator('.catalog-combo[data-category=os] [role=option]').first().textContent(),'Symbian OS 9.2');await page.locator('.catalog-combo[data-category=os] [role=option]').first().click();assert.equal(await page.locator('[data-effective=os]').inputValue(),'Symbian OS 9.2');await os.fill('Symbian OS 9.1');assert.equal(await os.evaluate(el=>el.checkValidity()),false);await os.fill('Symbian OS 9.2');await page.keyboard.press('Escape');assert.equal(await page.locator('#editor').evaluate(el=>el.open),true);
await page.evaluate(()=>{readDraft();});assert.equal(await page.evaluate(()=>draft.os),'Symbian OS 9.2');
// Existing model edits keep sibling overrides and legacy gallery data.
await page.evaluate(()=>{document.getElementById('editor').close();db.records=[{id:'a',kind:'phone',brand:'Nokia',model:'N73',alias:'N73-1',type:'RM-133',os:'Symbian OS 9.2',photos:['/media/old.jpg'],custom:{},instances:[{id:'u1',inv:'1',photos:[],type:''},{id:'u2',inv:'2',photos:[],type:'RM-ME'}]}];showEditor('a',1);});
await page.locator('[data-effective=type]').fill('RM-new');await page.locator('#editor-unit-select').selectOption('0');assert.equal(await page.locator('[data-effective=type]').inputValue(),'RM-133');assert.equal(await page.evaluate(()=>draft.instances[1].type),'RM-new');assert.equal(await page.evaluate(()=>draft.photos[0]),'/media/old.jpg');
await page.evaluate(()=>{dirty=false;closeEditor();sidebarState(true);});assert.equal(await page.locator('main').evaluate(el=>getComputedStyle(el).marginLeft),'0px');
// Empty and cleared phone forms must not block installation; real drafts must.
await page.evaluate(()=>{phoneDraft=null;catalogReturn=null;panelDirty=false;addPhone();closeEditor();});assert.equal(await page.evaluate(()=>hasUnsavedWork()),false);
await page.evaluate(()=>addPhone());await page.locator('[data-r=model]').fill('Unsaved test phone');await page.evaluate(()=>closeEditor());assert.equal(await page.evaluate(()=>hasUnsavedWork()),true);assert.match(await page.evaluate(()=>unsavedWorkReasons().join(' ')),/Add phone draft/);
page.once('dialog',d=>d.accept());await page.evaluate(()=>{addPhone();clearPhoneDraft();closeEditor();});assert.equal(await page.evaluate(()=>hasUnsavedWork()),false);assert.equal(await page.evaluate(()=>phoneDraft),null);
console.log('Update guard: untouched and cleared forms allow updates; real drafts identify Add phone as the source.');
// A long catalog must scroll inside Settings with aligned compact columns.
await page.evaluate(()=>{db.catalog.push(...Array.from({length:50},(_,i)=>({id:'brand'+i,category:'brand',name:i%2?'Sony Ericsson '+i:'Nokia '+i,description:i%2?'A description':'',specs:i%2?{Origin:'Test'}:{}})));catalogList('brand');});
await page.locator('[data-catalog-section=brand] .catalog-item-row').last().scrollIntoViewIfNeeded();
assert.equal(await page.locator('#panel-body').evaluate(el=>el.scrollTop>0&&el.scrollHeight>el.clientHeight),true);
const positions=await page.locator('[data-catalog-section=brand] .catalog-item-row').evaluateAll(rows=>rows.slice(0,3).map(r=>({height:r.getBoundingClientRect().height,x:[...r.children].map(c=>c.getBoundingClientRect().x)})));
assert.deepEqual(positions[0].x,positions[1].x);assert.deepEqual(positions[1].x,positions[2].x);assert.ok(positions.every(r=>r.height<=38));
await page.locator('[data-action=catalog-toggle][data-category=os]').click();assert.equal(await page.locator('[data-catalog-section=brand]').isVisible(),false);assert.equal(await page.locator('[data-catalog-section=os]').isVisible(),true);
console.log('Catalog DOM: long list scrolls, columns align, compact rows and single expanded category passed.');
// Filters use a single matching physical unit, and code searches ignore punctuation.
await page.evaluate(()=>{quickFilters={brand:'Nokia',color:'Black',os:'',location:'Shelf',state:''};});
assert.equal(await page.evaluate(()=>searchMatches({kind:'phone',brand:'Nokia',model:'N97 Mini',type:'RM-555',instances:[{color:'Black',location:'Box'},{color:'Silver',location:'Shelf'}]},'RM555')),false);
await page.evaluate(()=>quickFilters.location='Box');assert.equal(await page.evaluate(()=>searchMatches({kind:'phone',brand:'Nokia',model:'N97 Mini',type:'RM-555',instances:[{color:'Black',location:'Box',product_code:'0591234'}]},'Nokia RM555 0591234')),true);
// Choosing a photo changes only that unit; save-and-next submits and clears identifiers.
await page.evaluate(()=>{$('panel').close();panelRoute=null;panelDirty=false;phoneDraft=null;catalogReturn=null;quickFilters={};db.records[0].instances[0].photos=['https://example.com/a.jpg','https://example.com/b.jpg'];showEditor('a',0);});
await page.locator('[data-action=main-unit-photo]').click();assert.equal(await page.evaluate(()=>draft.instances[0].photos[0]),'https://example.com/b.jpg');
await page.evaluate(()=>{api=async(path,data)=>{if(path==='/api/record'){const r=clone(data.record);r.rev=2;db.records=[r];return r;}if(path==='/api/data')return db;return {};};});
await page.locator('#save-add-another').click();assert.equal(await page.locator('#editor').evaluate(el=>el.open),true);assert.equal(await page.evaluate(()=>mode),'add');assert.equal(await page.evaluate(()=>draft.instances.length),3);assert.equal(await page.evaluate(()=>addUnit.inv),'3');assert.equal(await page.evaluate(()=>addUnit.imei||''),'');assert.equal(await page.evaluate(()=>addUnit.photos.length),0);assert.equal(await page.evaluate(()=>db.records[0].instances[0].photos[0]),'https://example.com/b.jpg');
console.log('Filters, code search, main photo and Save and add another passed.');
await page.evaluate(()=>{dirty=false;phoneDraft=null;$('editor').close();db.records[0].battery='BL-6F';db.catalog.push({id:'bl6f',category:'battery',name:'BL-6F',description:'retained legacy description',source:'https://example.com',specs:{Legacy:'keep'},compatible:[]});catalogEditor('battery','bl6f');});
assert.equal(await page.locator('[data-battery-spec]').count(),8);assert.equal(await page.locator('#catalog-source').count(),0);assert.equal(await page.locator('#catalog-description').count(),0);assert.equal(await page.locator('[data-catalog-compatible]').count(),0);assert.ok((await page.locator('#panel-body').textContent()).includes('N73'));
await page.locator('[data-battery-spec=Voltage]').fill('3.7V');
await page.evaluate(()=>{api=async(path,data)=>{if(path==='/api/catalog'){db.catalog=db.catalog.map(x=>x.id===data.id?data:x);return data;}if(path==='/api/data')return db;return {};};});
await page.locator('[data-action=catalog-save]').click();assert.equal(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').specs.Voltage),'3.7V');assert.equal(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').specs.Legacy),'keep');assert.equal(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').description),'retained legacy description');
console.log('Battery properties, automatic models and preservation of hidden legacy data passed.');
// A real narrow viewport must show readable units instead of compressed desktop columns.
await page.evaluate(()=>{$('panel').close();panelRoute=null;panelDirty=false;dirty=false;currentView='all';db.settings.layout='list';db.settings.columns=columns.map(c=>c[0]);db.records[0].instances[0].box=true;db.records[0].instances[0].charger_present=false;db.records[0].instances[0].state='Ispravan';expanded.add('a');render();});
await page.setViewportSize({width:393,height:851});
assert.equal(await page.locator('#table-wrap').isVisible(),false);assert.equal(await page.locator('#mobile-list').isVisible(),true);
assert.equal(await page.locator('#quick-filters').isVisible(),false);await page.locator('#filter-toggle').click();assert.equal(await page.locator('#quick-filters').isVisible(),true);await page.locator('#filter-toggle').click();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
assert.equal(await page.locator('.mobile-primary-nav').evaluate(el=>el.getBoundingClientRect().height),66);
assert.ok(await page.locator('#mobile-list .state-working').count()>0);
assert.equal(await page.locator('#collection-table th[data-column-key=state]').count(),0);
assert.ok(await page.locator('#collection-table .unit-details-table .state-working').count()>0);
await page.screenshot({path:'mobile-collection-113.png',fullPage:true});
await page.evaluate(()=>{currentView='incomplete';render();});assert.equal(await page.locator('#completion-report').isVisible(),true);assert.match(await page.locator('#completion-report').textContent(),/Missing: Charger/);
await page.evaluate(()=>{currentView='all';showEditor('a',0);});assert.equal(await page.locator('[data-r=declared_parts]').count(),0);await page.locator('[data-u=for_parts]').check();await page.evaluate(()=>readDraft());assert.equal(await page.evaluate(()=>draft.instances[0].purpose),'Donor');await page.locator('[data-u=for_parts]').uncheck();await page.evaluate(()=>readDraft());assert.equal(await page.evaluate(()=>draft.instances[0].purpose),'Kolekcija');
console.log('Mobile widths, collapsed filters, bottom navigation, unit-only status, boxed completion and donor checkbox passed.');
await page.evaluate(()=>{dirty=false;$('editor').close();db.catalog.push({id:'alt1',category:'battery',name:'Test alternative 1',specs:{},compatible_batteries:[]},{id:'alt2',category:'battery',name:'Test alternative 2',specs:{},compatible_batteries:[]});catalogEditor('battery','bl6f');});
await page.locator('[data-battery-compatible=alt1]').check();await page.locator('[data-battery-compatible=alt2]').check();await page.locator('[data-action=catalog-save]').click();
assert.deepEqual(await page.evaluate(()=>db.catalog.find(x=>x.id==='bl6f').compatible_batteries),['alt1','alt2']);
assert.match(await page.evaluate(()=>batteryCell('BL-6F')),/Test alternative 1/);assert.match(await page.evaluate(()=>batteryCell('BL-6F')),/Test alternative 2/);
assert.match(await page.evaluate(()=>catalogItems('battery')),/Nominal Capacity/);assert.match(await page.evaluate(()=>catalogItems('battery')),/3.7V/);
await page.evaluate(()=>{$('panel').close();panelDirty=false;panelRoute=null;render();});await page.setViewportSize({width:1700,height:950});
assert.equal(await page.locator('#collection-table .unit-table-row [data-column=os]').first().evaluate(el=>getComputedStyle(el).whiteSpace),'nowrap');
assert.equal(await page.locator('#collection-table .unit-extra-row').count(),0);
await page.evaluate(()=>{db.records[0].os='Symbian OS 9.2, S60 rel. 3.1';db.records[0].instances[0].os='';db.records[0].instances[0].location='On shelf';render();});
const row=page.locator('#collection-table .unit-table-row').first();
for(const key of ['location','box','state','rating','note'])assert.equal(await row.locator('[data-column='+key+']').count(),1);
const osCell=row.locator('[data-column=os]');
assert.match(await osCell.textContent(),/Symbian OS 9.2, S60 rel. 3.1/);
assert.equal(await osCell.locator('button').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.equal(await row.locator('[data-column=image] small').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
await page.screenshot({path:'desktop-collection-114.png',fullPage:true});
console.log('Battery summaries, multi-selection, automatic alternatives and compact expanded rows passed.');
console.log('DOM: one field per property, search/select/reject, Escape, effective unit switching, retained gallery, collapsed layout passed.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
