const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const elements=new Map(),handlers={};
function node(id){if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',hidden:false,style:{},dataset:{},classList:{toggle(){},remove(){},add(){}},setAttribute(){},addEventListener(type,fn){handlers[id+':'+type]=fn;},querySelectorAll(){return []},querySelector(){return null},show(){this.open=true;this.modal=false},showModal(){this.open=true;this.modal=true},close(){this.open=false}});return elements.get(id);}
const context=vm.createContext({document:{getElementById:node,querySelectorAll(){return []},addEventListener(type,fn){handlers['document:'+type]=fn;},documentElement:{dataset:{}}},window:{addEventListener(){}},location:{hash:''},console,setTimeout,clearTimeout,URLSearchParams,confirm:()=>true});
let source=fs.readFileSync(require('node:path').join(__dirname,'../web/app.js'),'utf8');source=source.slice(0,source.lastIndexOf('boot().then('));vm.runInContext(source,context);
vm.runInContext(`db={version:'1.3.0',settings:{layout:'cards',columns:['brand','model','inv'],options:{},views:[]},catalog:[],records:[{id:'a',kind:'phone',brand:'Nokia',model:'N73',battery:'BL-5J',charger:'2mm',instances:[{id:'u1',inv:'1',condition:'U kolekciji',state:'Ispravan',color:'Silver',edition:'Standard',imei:'123456789012345',photos:[]}]}]};`,context);
vm.runInContext('render()',context);assert.equal(node('table-wrap').hidden,true);assert.equal(node('card-grid').hidden,false);assert.match(node('card-grid').innerHTML,/View units/);assert.match(node('card-grid').innerHTML,/N73/);
const units=vm.runInContext('unitTiles(db.records[0])',context);assert.ok(!units.includes('<thead>'));assert.ok(!units.includes('123456789012345'));assert.match(units,/Copy/);
vm.runInContext("currentView='part';render()",context);assert.equal(node('card-grid').hidden,true);
vm.runInContext("currentView='all';db.settings.layout='list';render()",context);assert.equal(node('table-wrap').hidden,false);assert.match(node('collection-table').innerHTML,/draggable="true"/);
console.log('UI: cards/list, sidebar filter, masked IMEI, unit details and draggable headers passed.');

vm.runInContext("db.settings.custom_fields=[];db.trash=[];db.settings.options={os:['Symbian']};",context);
vm.runInContext("addPhone();draft.brand='Nokia';draft.model='N97 Mini';draft.os='New OS';draft.instances[0].color='Silver';draft.instances[0].product_code='0590012';draft.instances[0].photos=['/media/photo.jpg'];dirty=true;closeEditor();",context);
assert.equal(node('editor').open,false);
vm.runInContext("db.settings.options.os.push('New OS');addPhone();",context);
assert.equal(vm.runInContext('draft.model',context),'N97 Mini');
assert.equal(vm.runInContext('draft.instances[0].product_code',context),'0590012');
assert.equal(vm.runInContext('draft.instances[0].photos[0]',context),'/media/photo.jpg');
assert.match(node('datalists').innerHTML,/New OS/);
assert.match(node('editor-content').innerHTML,/Clear data/);
vm.runInContext('clearPhoneDraft()',context);
assert.equal(vm.runInContext('draft.brand',context),'');assert.equal(vm.runInContext('draft.instances[0].photos.length',context),0);
vm.runInContext("db.catalog=[{id:'os1',category:'os',name:'Symbian',description:'',source:'',specs:{}}];catalogList('os');catalogEditor('os','os1');closePanel();",context);
assert.equal(vm.runInContext('panelRoute.kind',context),'settings');assert.equal(node('panel').modal,false);
assert.equal(node('panel-title').textContent,'Settings');
vm.runInContext('panelDirty=true',context);context.confirm=()=>false;
vm.runInContext('closePanel()',context);assert.equal(vm.runInContext('panelRoute.kind',context),'settings');context.confirm=()=>true;
handlers['document:click']({target:{closest(){return {dataset:{action:'nav-view',view:'phone'}}}}});
assert.equal(node('panel').open,false);assert.equal(vm.runInContext('currentView',context),'phone');
assert.match(vm.runInContext('unitHTML({product_code:"0590012",photos:[]},0,true)',context),/value="0590012"/);
console.log('UI: retained draft fields/photos, refreshed catalogs, Clear data, catalog back navigation, unsaved guard and sidebar navigation passed.');

const unitForm=vm.runInContext('unitHTML(blankUnit(),0,true)',context);
assert.ok(!unitForm.includes('data-u="type"'));assert.ok(!unitForm.includes('Originality'));
assert.match(unitForm,/Wanted/);assert.match(unitForm,/Purchase price \(KM\)/);assert.ok(!unitForm.includes('data-u="currency"'));assert.ok(!unitForm.includes('value="CHF"'));
assert.equal(vm.runInContext('opts.condition.length',context),2);
const imageCell=vm.runInContext("cell(db.records[0],'image')",context);
assert.match(imageCell,/expand-model/);assert.ok(!vm.runInContext("cell(db.records[0],'model')",context).includes('data-action="expand"'));
vm.runInContext("catalogList('os')",context);assert.match(node('panel-body').innerHTML,/data-action="catalog-delete" data-id="os1"/);
const updates=vm.runInContext('updateContents()',context);assert.match(updates,/Check for updates/);assert.ok(!updates.includes('<dialog'));
vm.runInContext("addPhone();draft.model='Backdrop draft';dirty=true",context);
const editor=node('editor');editor.getBoundingClientRect=()=>({left:100,right:500,top:100,bottom:500});
handlers['editor:click']({target:editor,clientX:50,clientY:50});assert.equal(editor.open,false);
assert.equal(vm.runInContext('phoneDraft.model',context),'Backdrop draft');
vm.runInContext('addPhone()',context);handlers['editor:click']({target:editor,clientX:150,clientY:150});assert.equal(editor.open,true);
console.log('UI: KM, two ownership choices, removed duplicate fields, leading expand control, catalog row deletion, inline updates and backdrop draft retention passed.');
vm.runInContext("draft.model='Escape draft';dirty=true",context);
handlers['document:keydown']({key:'Escape',preventDefault(){}});
assert.equal(editor.open,false);assert.equal(vm.runInContext('phoneDraft.model',context),'Escape draft');
vm.runInContext("catalogList('os');catalogEditor('os','os1')",context);
handlers['document:keydown']({key:'Escape',preventDefault(){}});
assert.equal(vm.runInContext('panelRoute.kind',context),'settings');
assert.equal(vm.runInContext("amountCurrency({currency:'CHF',price:25})",context),'CHF');
console.log('UI: Escape retains phone draft, returns to catalog list, and old currencies remain labelled correctly.');
vm.runInContext("addPhone();draft.model='Catalog draft';dirty=true",context);
handlers['document:click']({target:{closest(){return {dataset:{action:'field-catalog',category:'os'}}}}});
assert.equal(node('editor').open,false);assert.equal(vm.runInContext('catalogReturn.draft.model',context),'Catalog draft');
vm.runInContext('returnToPhone()',context);assert.equal(editor.open,true);assert.equal(vm.runInContext('draft.model',context),'Catalog draft');
assert.match(node('editor-content').innerHTML,/data-action="field-catalog" data-category="os"/);
vm.runInContext(`db.catalog.push({id:'silver',category:'color',name:'silver'});db.records[0].alias='N73-1';db.records[0].type='RM-133';db.records[0].os='Symbian';db.records[0].wiki='https://en.wikipedia.org/wiki/N73';db.records[0].instances.push({...db.records[0].instances[0],id:'u2',inv:'2',color:'Black',alias:'N73-ME',os:'Symbian ME',edition:'Music Edition',wiki:'https://en.wikipedia.org/wiki/Music_Edition'});`,context);
const aligned=vm.runInContext("expandedRow(db.records[0],['image','alias','colors','editions','os','wiki','actions'])",context);
assert.equal((aligned.match(/class="unit-table-row"/g)||[]).length,2);
assert.match(aligned,/N73-1/);assert.match(aligned,/N73-ME/);assert.match(aligned,/>Silver</);assert.match(aligned,/Music Edition/);assert.match(aligned,/Symbian ME/);assert.match(aligned,/wiki\/Music_Edition/);
assert.equal(vm.runInContext("value(db.records[0],'alias')",context),'N73-1, N73-ME');
assert.equal(vm.runInContext("value(db.records[0],'os')",context),'Symbian, Symbian ME');
assert.match(vm.runInContext('backupContents()',context),/restore-file/);
assert.match(vm.runInContext('backupContents()',context),/create-backup/);
console.log('UI: aligned unit columns, individual overrides, inherited values, color casing and inline backup controls passed.');
(async()=>{
 const saved=new Map([['mpl-update-target','1.4.1']]);let reloads=0,calls=0;
 context.sessionStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)};
 context.location.reload=()=>reloads++;
 context.setTimeout=fn=>{fn();return 0};
 context.fetch=async()=>({ok:true,json:async()=>({version:++calls===1?'1.3.0':'1.4.1'})});
 await vm.runInContext('reconnectAfterRestart()',context);
 assert.equal(calls,2);assert.equal(reloads,1);assert.equal(saved.get('mpl-update-complete'),'1.4.1');
 saved.delete('mpl-update-complete');reloads=0;
 context.fetch=async()=>({ok:true,json:async()=>({version:'1.3.0'})});
 await vm.runInContext('reconnectAfterRestart()',context);
 assert.equal(node('startup-status').style.display,'grid');assert.equal(node('startup-retry').hidden,false);
 assert.equal(reloads,0);assert.match(node('update-result').textContent,/not confirmed as installed/);
 assert.equal(saved.has('mpl-update-complete'),false);
 console.log('UI: restart waits for target version; old version produces persistent failure instead of success.');
 context.fetch=async()=>({ok:true,json:async()=>({path:'C:\\Backup',parent:'C:\\',roots:['C:\\'],folders:[{name:'Photos',path:'C:\\Backup\\Photos'}]})});
 await vm.runInContext("openFolderPicker('backup-primary')",context);
 assert.ok(!node('folder-picker').open);
 assert.equal(node('backup-primary').value,'C:\\Backup');assert.ok(!node('folder-picker').open);
 console.log('UI: host folder picker opens and selects a backup destination without discarding settings.');

 vm.runInContext("dirty=false;phoneDraft=null;panelDirty=false;catalogReturn=null;db=null",context);
 context.fetch=async()=>({ok:true,json:async()=>({version:'1.6.2',instance:'new'})});reloads=0;
 await vm.runInContext('checkConnection()',context);assert.equal(reloads,1);
 vm.runInContext("phoneDraft={model:'Unsaved'}",context);reloads=0;
 await vm.runInContext('checkConnection()',context);assert.equal(reloads,0);assert.match(node('connection-message').textContent,/unsaved draft/);
 context.fetch=async()=>{throw Error('offline')};await vm.runInContext('checkConnection()',context);
 assert.match(node('connection').textContent,/Offline/);
 context.fetch=async()=>({ok:true,json:async()=>({version:'1.12.0',instance:'new'})});
 await vm.runInContext('checkConnection()',context);assert.equal(node('connection-banner').hidden,true);
 console.log('UI: stale pages reload, unsaved drafts block reload, and connection loss/recovery is visible.');

 saved.set('mpl-install-target','1.7.0');reloads=0;let installPoll=0;
 context.fetch=async()=>{
  installPoll++;
  if(installPoll===2)throw Error('server stopped for install');
  return {ok:true,json:async()=>installPoll===1?{version:'1.6.1',update_job:{status:'downloading',version:'1.7.0',progress:50,message:'Downloading'}}:{version:'1.7.0',update_job:{status:'completed',version:'1.7.0'}}};
 };
 await vm.runInContext('watchInstallation()',context);
 assert.equal(reloads,1);assert.equal(installPoll,3);assert.equal(saved.has('mpl-install-target'),false);
 saved.set('mpl-install-target','1.7.0');reloads=0;
 context.fetch=async()=>({ok:true,json:async()=>({version:'1.6.1',update_job:{status:'failed',version:'1.7.0',message:'Installer checksum mismatch'}})});
 await vm.runInContext('watchInstallation()',context);
 assert.equal(reloads,0);assert.match(node('startup-detail').textContent,/checksum/);
 console.log('UI: independent update survives server outage, reloads only after verified completion and retains installer failure details.');
})().catch(error=>{console.error(error);process.exitCode=1});
